# Generated by Django 3.1.7 on 2022-05-22 15:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('Chairman', 'Chairman'), ('Admin', 'Admin'), ('Head Judge', 'Head Judge'), ('Programme Judge', 'Programme Judge'), ('Programme Coordinator', 'Programme Coordinator'), ('Attendee', 'Attendee')], max_length=64)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('email', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('vote_status', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendees',
                'verbose_name_plural': 'Attendees',
                'db_table': 'Attendee',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conf_id', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='conf_no')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(default='Conference Content ........', max_length=128)),
                ('rule', models.CharField(default='Conference Rule ........', max_length=9000)),
            ],
            options={
                'verbose_name': 'Conference',
                'db_table': 'Conference',
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('posterID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('authorName', models.CharField(max_length=128)),
                ('authorEmail', models.CharField(max_length=128, unique=True)),
                ('supervisorName', models.CharField(max_length=128)),
                ('poster_file', models.ImageField(upload_to='posters')),
            ],
            options={
                'db_table': 'Poster',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('programme_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('abbr', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Programme',
                'db_table': 'Programme',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False, verbose_name='conf_no')),
                ('rule', models.CharField(default='Conference Rule', max_length=1000)),
                ('num_of_judges', models.IntegerField(default=18)),
                ('num_of_head_judge', models.IntegerField(default=2)),
                ('num_of_fir_prize', models.IntegerField(default=3)),
                ('num_of_sec_prize', models.IntegerField(default=5)),
                ('num_of_thr_prize', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Rule',
                'db_table': 'Rule',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.user')),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Admins',
                'verbose_name_plural': 'Admins',
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.user')),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Chairmen',
                'verbose_name_plural': 'Chairmen',
                'db_table': 'Chairman',
            },
        ),
        migrations.CreateModel(
            name='DivisionWinnerPoster',
            fields=[
                ('posterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='poster', serialize=False, to='cms.poster')),
                ('divisionName', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'DivisionWinnerPoster',
            },
        ),
        migrations.CreateModel(
            name='HeadJudge',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.user')),
                ('password', models.CharField(max_length=10)),
                ('score_status', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'HeadJudges',
                'verbose_name_plural': 'HeadJudges',
                'db_table': 'HeadJudge',
            },
        ),
        migrations.CreateModel(
            name='LuckyDrawer',
            fields=[
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.attendee')),
                ('prize_level', models.IntegerField()),
            ],
            options={
                'db_table': 'LuckyDrawer',
            },
        ),
        migrations.CreateModel(
            name='PosterInternalUse',
            fields=[
                ('posterID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.poster')),
                ('judgeScores', models.JSONField(default={})),
            ],
            options={
                'db_table': 'PosterInternalUse',
            },
        ),
        migrations.CreateModel(
            name='PosterPublicUse',
            fields=[
                ('posterID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.poster')),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'PosterPublicUse',
            },
        ),
        migrations.CreateModel(
            name='ProgrammeWinnerPoster',
            fields=[
                ('posterID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.poster')),
                ('scoresByHJ', models.JSONField(default={})),
            ],
            options={
                'db_table': 'ProgrammeWinnerPoster',
            },
        ),
        migrations.AddField(
            model_name='poster',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.programme'),
        ),
        migrations.CreateModel(
            name='ProgrammeJudge',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.user')),
                ('password', models.CharField(max_length=10)),
                ('score_status', models.BooleanField(default=0)),
                ('program_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cms.programme')),
            ],
            options={
                'verbose_name': 'ProgrammeJudges',
                'verbose_name_plural': 'ProgrammeJudges',
                'db_table': 'ProgrammeJudge',
            },
        ),
        migrations.CreateModel(
            name='PopularPoster',
            fields=[
                ('posterID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.poster')),
                ('programmeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.programme')),
            ],
            options={
                'db_table': 'PopularPoster',
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.user')),
                ('password', models.CharField(max_length=10)),
                ('program_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cms.programme')),
            ],
            options={
                'verbose_name': 'Coordinators',
                'verbose_name_plural': 'Coordinators',
                'db_table': 'Coordinator',
            },
        ),
    ]
